Feature/extra chars
BoOmka/discord-reactor pull request #1
Opened 2021-06-24 20:29 UTC by Lagbjorn

- Добавлена поддержка спецсимволов
- Добавлены символы `1234567890!?*#`
- Пользователю выводится ответ со скорректированным текстом

2021-06-26 07:12 UTC, BoOmka requested changes

2021-06-26 07:12 UTC, BoOmka commented on handlers.py
> +                with open(f"emojis/{_emoji.file}", "rb") as f:
#простокоммент

Можно будет потом предзагружать данные в память на старте

2021-06-26 07:12 UTC, BoOmka commented on helpers.py
> +    if len(text) > 20:
Нужно тесткейсы дописать в тесты. Положительный и отрицательный

2021-06-26 07:12 UTC, BoOmka commented on models.py
> +    Emojie dataclass allows to associate char with corresponding default emojies
#typo

Emojie -> Emoji

2021-06-26 07:12 UTC, BoOmka commented on models.py
> +class Emoji:
#nice

2021-06-27 07:14 UTC, Lagbjorn commented on models.py
> +    Emojie dataclass allows to associate char with corresponding default emojies
Fixed in 03567af

2021-06-27 07:14 UTC, Lagbjorn commented on helpers.py
> +    if len(text) > 20:
Done in ee222de

2021-06-27 08:18 UTC, merged